<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="css/jquery-ui.min.css">
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <script src="js/jquery.min.js"></script>
        <script src="js/jquery-ui.min.js"></script>
    </head>
    <body>
        <div class="ui-widget">
            <label for="time-zone">Time Zone Search</label>
            <input id="time-zone" type="text" class="time-zone-search" name="time-zone" />
        </div>
        <script src="js/time-zone.js"></script>
    </body>
</html>
